import {config} from './config.js';
import {localDate,addDays,weekStart,minutes,lessonTotals,previousAims,validateBooking,splitTrack,escapeHtml as h} from './core.js';

const today=new Date();
const people=[{id:'p1',name:'Alex Morgan',email:'alex@example.com',colour:'#dcf2d0'},{id:'p2',name:'Jamie Taylor',email:'jamie@example.com',colour:'#dbeafa'},{id:'p3',name:'Sam Wilson',email:'sam@example.com',colour:'#f5e6ce'}];
const sampleLesson=(id,pupil,day,hour,duration)=>({id,pupil_id:pupil,starts_at:new Date(`${localDate(addDays(weekStart(today),day))}T${hour}:00:00`).toISOString(),ends_at:new Date(new Date(`${localDate(addDays(weekStart(today),day))}T${hour}:00:00`).getTime()+duration*3600000).toISOString(),status:'scheduled',paid:id==='l1',fee:80,pickup:{label:'Station car park',lat:51.4545,lng:-2.5879},dropoff:{label:'Station car park',lat:51.4545,lng:-2.5879},objectives:'Build confidence at roundabouts',improved:'',needs_work:'',other:'',next_aims:'',travel_before_minutes:20,travel_source:'manual'});
const state={demo:!config.supabaseUrl,role:'admin',view:'diary',week:weekStart(today),pupils:people,lessons:[sampleLesson('l1','p1',1,'09',2),sampleLesson('l2','p2',1,'12',1.5),sampleLesson('l3','p3',2,'10',2),sampleLesson('l4','p1',3,'14',2),sampleLesson('l5','p2',4,'09',2)],resources:[],links:[],points:[],selected:null,busy:false};
const samplePast={...sampleLesson('l0','p1',-5,'09',1.5),status:'completed',start_mileage:12400,end_mileage:12418.4,paid:true,objectives:'Junction approach and observation',improved:'Earlier mirror checks before slowing down.',needs_work:'Consistent approach speed at closed junctions.',other:'',next_aims:'Practise meeting traffic on narrow roads'};
samplePast.started_at=samplePast.starts_at;samplePast.ended_at=samplePast.ends_at;state.lessons.push(samplePast);
const sampleCoordinates=[[51.45451,-2.58793],[51.4549,-2.5875],[51.4554,-2.5869],[51.4559,-2.5862],[51.4564,-2.5855],[51.4568,-2.5848],[51.4565,-2.5841],[51.4561,-2.5835],[51.4556,-2.5828],[51.4551,-2.5822]];
state.points=sampleCoordinates.map(([lat,lng],i)=>({id:`sample-${i}`,lesson_id:'l0',lat,lng,accuracy:5,recorded_at:new Date(new Date(samplePast.started_at).getTime()+i*20000).toISOString()}));
let db=null,map=null,watchId=null,wakeLock=null,trackingLesson=null,trackingMessage='',pointQueue=[],syncTimer=null;
const $=selector=>document.querySelector(selector);
const pupil=id=>state.pupils.find(p=>p.id===id);
const dateLabel=(d,opts={day:'numeric',month:'short'})=>new Date(d).toLocaleDateString('en-GB',opts);
const clock=d=>new Date(d).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:config.currency}).format(n||0);
const icon=name=>({diary:'▦',pupils:'◉',resources:'▤',progress:'↗'}[name]||'•');
function toast(message,error=false){ $('#toast').textContent=message;$('#toast').className=error?'show error':'show';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').className='',6500); }
function shell(){
 $('#app').innerHTML=`<aside class="sidebar">${config.name?`<span class="brand">${h(config.name)}</span>`:''}<div class="workspace-label">${state.role==='admin'?'INSTRUCTOR WORKSPACE':'PUPIL ACCOUNT'}</div><nav>${(state.role==='admin'?['diary','pupils','resources']:['diary','progress']).map(v=>`<button class="nav-item ${state.view===v?'selected':''}" data-view="${v}"><span>${icon(v)}</span>${v==='diary'?'Lesson diary':v==='resources'?'Teaching library':v==='progress'?'My progress':'Pupils'}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="avatar">${state.role==='admin'?'IN':'AL'}</div><div><strong>${state.role==='admin'?'Instructor':'Pupil account'}</strong><small>${state.demo?'Sample workspace':'Private workspace'}</small></div></div></aside><main><div class="topbar"><span>${dateLabel(today,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</span><div>${state.demo?'<span class="demo-pill">PREVIEW · SAMPLE DATA</span> <button class="text-button" id="switch-role">View as '+(state.role==='admin'?'pupil':'instructor')+'</button>':'<button class="text-button" id="account-password">Password</button> <button class="text-button" id="logout">Sign out</button>'}</div></div><div id="content"></div></main>`;
 if(pointQueue.length){const pending=document.createElement('div');pending.className='notice warning';pending.innerHTML=`${pointQueue.length} route points are waiting to save. <button id="retry-sync">Retry saving</button>`;$('#content').before(pending);$('#retry-sync').onclick=()=>safely(async()=>{await flushPoints();render();toast('Route points saved.');});}
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render();});
 $('#switch-role')?.addEventListener('click',()=>{state.role=state.role==='admin'?'pupil':'admin';state.view='diary';render();});
 $('#logout')?.addEventListener('click',signOut);
 $('#account-password')?.addEventListener('click',()=>safely(()=>passwordScreen(false)));
}
function visibleLessons(){return state.role==='admin'?state.lessons:state.lessons.filter(l=>l.pupil_id===(state.pupilId||'p1'));}
function render(){if(map){map.remove();map=null;}shell();if(state.view==='diary')renderDiary();else if(state.view==='pupils')renderPupils();else if(state.view==='resources')renderResources();else renderProgress(state.role==='admin'?state.progressPupil:(state.pupilId||'p1'));}
function renderDiary(){
 const lessons=visibleLessons().filter(l=>l.status!=='cancelled');
 const weekLessons=lessons.filter(l=>new Date(l.ends_at)>state.week&&new Date(l.starts_at)<addDays(state.week,7));
 const hours=weekLessons.reduce((n,l)=>n+minutes(l.starts_at,l.ends_at)/60,0);
 $('#content').innerHTML=`<div class="heading"><div><h1>Lesson diary</h1></div>${state.role==='admin'?'<button class="primary" id="book">＋ Book a lesson</button>':''}</div><div class="stats"><div><span>Lessons this week</span><strong>${weekLessons.length}<small>booked</small></strong></div><div><span>Driving time</span><strong>${hours.toFixed(1)}<small>hours planned</small></strong></div><div><span>${state.role==='admin'?'Awaiting payment':'Lesson payments'}</span><strong>${money(weekLessons.filter(l=>!l.paid).reduce((n,l)=>n+Number(l.fee),0))}<small>outstanding this week</small></strong></div></div><section class="diary-panel"><div class="calendar-toolbar"><div><h2>${dateLabel(state.week)} – ${dateLabel(addDays(state.week,6),{day:'numeric',month:'short',year:'numeric'})}</h2><span class="muted">${Intl.DateTimeFormat().resolvedOptions().timeZone.replaceAll('_',' ')}</span></div><div class="calendar-actions"><button id="previous" aria-label="Previous week">‹</button><button id="today">Today</button><button id="next" aria-label="Next week">›</button></div></div><div class="calendar-scroll"><div class="calendar"><div class="time-head"></div>${Array.from({length:7},(_,i)=>{const d=addDays(state.week,i);return `<div class="day-head ${localDate(d)===localDate(today)?'is-today':''}"><span>${dateLabel(d,{weekday:'short'})}</span><strong>${d.getDate()}</strong></div>`;}).join('')}<div class="time-column">${Array.from({length:24},(_,i)=>`<span style="top:${i*72}px">${String(i).padStart(2,'0')}:00</span>`).join('')}</div>${Array.from({length:7},(_,i)=>`<div class="day-column">${weekLessons.filter(l=>new Date(l.starts_at)<addDays(state.week,i+1)&&new Date(l.ends_at)>addDays(state.week,i)).map(l=>lessonCard(l,addDays(state.week,i))).join('')}</div>`).join('')}</div></div><footer class="calendar-legend"><span><i class="legend lesson"></i>Scheduled lesson</span><span><i class="legend travel"></i>Travel time</span><span>✓ Paid</span></footer></section>${state.demo?'<p class="preview-note">This preview uses fictional pupils. Changes last until you reload. Connect Supabase before entering real pupil information.</p>':''}`;
 $('#previous').onclick=()=>{state.week=addDays(state.week,-7);render();};$('#next').onclick=()=>{state.week=addDays(state.week,7);render();};$('#today').onclick=()=>{state.week=weekStart(today);render();};$('#book')?.addEventListener('click',()=>bookLesson());
 document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>openLesson(b.dataset.lesson));
 const earliest=Math.min(8,...weekLessons.map(l=>new Date(l.starts_at).getHours()));$('.calendar-scroll').scrollTop=Math.max(0,earliest-1)*72;if(matchMedia('(max-width:750px)').matches&&today>=state.week&&today<addDays(state.week,7))$('.calendar-scroll').scrollLeft=((today.getDay()+6)%7)*150;
}
function lessonCard(l,day){const start=Math.max(new Date(l.starts_at),day),end=Math.min(new Date(l.ends_at),addDays(day,1)),top=minutes(day,start)*1.2,height=minutes(start,end)*1.2,p=pupil(l.pupil_id);return `${l.travel_before_minutes&&localDate(l.starts_at)===localDate(day)?`<div class="travel-block" style="top:${top-l.travel_before_minutes*1.2}px;height:${l.travel_before_minutes*1.2}px"><span>${l.travel_before_minutes} min travel${l.travel_source==='manual'?' · allowance':l.travel_source==='review'?' · recheck':''}</span></div>`:''}<button class="lesson-card" data-lesson="${l.id}" style="top:${top}px;height:${height}px;--lesson-colour:${p?.colour||'#dceefa'}"><span class="lesson-time">${clock(l.starts_at)} – ${clock(l.ends_at)} <b>${l.paid?'✓':''}</b></span><strong>${h(p?.name||'Pupil')}</strong><span class="lesson-topic">${h(l.objectives||'Objectives to be added')}</span><span class="lesson-place">⌖ ${h(l.pickup.label)}</span>${l.status==='active'?'<span class="live-label">LESSON IN PROGRESS</span>':''}</button>`;}
function dialog(title,body){if(map){map.remove();map=null;}const el=$('#modal');el.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${h(title)}</h2><button type="button" id="close-dialog" aria-label="Close">✕</button></div><div class="dialog-body">${body}</div>`;$('#close-dialog').onclick=()=>el.close();if(!el.open)el.showModal();el.onclose=()=>{if(map){map.remove();map=null;}if(state.view==='progress')renderProgress(state.role==='admin'?state.progressPupil:(state.pupilId||'p1'));};}
async function safely(action){if(state.busy)return;state.busy=true;const buttons=[...document.querySelectorAll('dialog button[type=submit]:not(:disabled)')];buttons.forEach(b=>b.disabled=true);try{await action();}catch(e){toast(e.message||'Something went wrong. Please try again.',true);}finally{state.busy=false;buttons.forEach(b=>b.disabled=false);}}
async function allRows(table){let result=[],page=0;while(true){const {data,error}=await db.from(table).select('*').order('id').range(page*1000,page*1000+999);if(error)throw error;result.push(...data);if(data.length<1000)return result;page++;}}
async function reloadData(){if(state.demo)return;const [pupils,lessons,resources,links]=await Promise.all(['pupils','lessons','resources','lesson_resources'].map(allRows));Object.assign(state,{pupils,lessons,resources,links});}
async function rpc(name,args){const {data,error}=await db.rpc(name,args);if(error)throw error;return data;}
let recoveryPending=false;
const recoveryKey=`diary-password-recovery:${config.supabaseUrl}`;
function rememberRecovery(value){
 recoveryPending=value;
 try{if(value)sessionStorage.setItem(recoveryKey,'1');else sessionStorage.removeItem(recoveryKey);}catch{}
}
function authError(error){
 if(error?.code==='invalid_credentials')return 'Email or password is incorrect.';
 if(error?.code==='email_not_confirmed')return 'Confirm your email before signing in. Open the confirmation email sent when you created your account.';
 if(error?.status===429||/rate limit/i.test(error?.message||''))return 'Too many attempts or emails. Wait before trying again. Email limits also apply to password reset and account confirmation.';
 if(error?.code==='otp_expired')return 'This email link has expired or has already been used. Request a new password reset link.';
 return error?.message||'Could not complete the request. Please try again.';
}
async function init(){
 if(state.demo){render();registerTools();return;}
 $('#app').innerHTML='<div class="loading">Loading…</div>';
 const fragment=new URLSearchParams(location.hash.slice(1));
 const linkError=fragment.has('error')?(fragment.get('error_code')==='otp_expired'?'This email link has expired or has already been used. Sign in with your password or request a new password reset link.':'This email link could not be used. Sign in or request a new password reset link.'):'';
 const recoveryLink=fragment.get('type')==='recovery';
 // Remove failed callback parameters; let Supabase consume successful callbacks.
 if(linkError){history.replaceState(null,'',location.pathname+location.search);rememberRecovery(false);}
 try{
  const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2.57.4');
  db=createClient(config.supabaseUrl,config.supabasePublishableKey);
  // Keep this callback synchronous: Auth API calls inside it can deadlock.
  db.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY')rememberRecovery(true);if(event==='SIGNED_OUT')rememberRecovery(false);});
  const {data:{session},error}=await db.auth.getSession();if(error)throw error;
  if(!session){rememberRecovery(false);authScreen(linkError);return;}
  try{recoveryPending=recoveryPending||sessionStorage.getItem(recoveryKey)==='1';}catch{}
  if(recoveryLink||recoveryPending){rememberRecovery(true);await passwordScreen(true);return;}
  await openWorkspace();
 }catch(e){authScreen(authError(e));}
}
async function openWorkspace(){
 try{
  await rpc('claim_pupil_account',{});
  state.role=(await rpc('is_instructor',{}))?'admin':'pupil';
  await reloadData();if(state.role==='pupil'){state.pupilId=state.pupils[0]?.id;if(!state.pupilId){authScreen('Your account is not linked to a pupil yet. Ask your instructor to add this email address.');return;}}
  render();registerTools();if(pointQueue.length){toast('Unsynced route points found. Open the active lesson and resume recording to retry saving.',true);}
 }catch(e){authScreen(`Could not open the diary: ${e.message}`);}
}
function passwordFields(){return '<label>Password<input name="password" type="password" autocomplete="new-password" minlength="8" required></label><label>Confirm password<input name="confirm_password" type="password" autocomplete="new-password" minlength="8" required></label><p class="help">Use at least 8 characters.</p>';}
function checkPasswords(form){
 const password=form.elements.password.value;
 if(password.length<8)throw Error('Use at least 8 characters for your password.');
 if(password!==form.elements.confirm_password.value)throw Error('The passwords do not match.');
 return password;
}
function bindAuthForm(form,action){
 form.onsubmit=async e=>{
  e.preventDefault();
  const button=form.querySelector('button[type="submit"]'),result=form.querySelector('[role="status"]');
  if(button.disabled||!form.reportValidity())return;
  button.disabled=true;result.textContent='';result.className='help';
  try{await action(form,result);}catch(error){result.textContent=authError(error);result.className='error-message';}
  finally{button.disabled=false;}
 };
}
function authScreen(message='',mode='signin',email=''){
 const signup=mode==='signup',reset=mode==='reset';
 $('#app').innerHTML=`<div class="auth"><h1>${signup?'Create pupil account':reset?'Set or reset password':'Sign in'}</h1>${signup?'<p class="help">Use the email address your instructor has added for you.</p>':reset?'<p class="help">We will email you a link to choose a password.</p>':''}${message?`<p class="error-message" role="alert">${h(message)}</p>`:''}<form id="sign-in"><label>Email address<input name="email" type="email" autocomplete="email" autocapitalize="none" spellcheck="false" value="${h(email)}" required></label>${reset?'':signup?passwordFields():'<label>Password<input name="password" type="password" autocomplete="current-password" required></label>'}<button type="submit" class="primary">${signup?'Create account':reset?'Send password reset email':'Sign in'}</button><p id="auth-result" role="status" class="help"></p></form>${mode==='signin'?'<button id="forgot-password" class="text-button">Set or reset password</button><button id="create-account" class="text-button">Create pupil account</button>':'<button id="back-signin" class="text-button">Back to sign in</button>'}<button id="clear-session" class="text-button">Use a different account</button></div>`;
 const form=$('#sign-in');
 bindAuthForm(form,async(form,result)=>{
  if(!db)throw Error('Sign-in is unavailable. Reload the page and try again.');
  const email=form.elements.email.value.trim(),redirect=location.origin+location.pathname;
  if(reset){
   const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:redirect});if(error)throw error;
   result.textContent='If an account exists for this email, a password reset link has been sent. Open the newest email once.';
  }else if(signup){
   const password=checkPasswords(form);
   const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:redirect}});if(error)throw error;
   form.elements.password.value='';form.elements.confirm_password.value='';
   if(data.session){rememberRecovery(false);await openWorkspace();}
   else result.textContent='Check your email to confirm your account, then sign in with your password. If you already have an account, use Set or reset password.';
  }else{
   const {error}=await db.auth.signInWithPassword({email,password:form.elements.password.value});if(error)throw error;
   form.elements.password.value='';rememberRecovery(false);await openWorkspace();
  }
 });
 $('#forgot-password')?.addEventListener('click',()=>authScreen('','reset',form.elements.email.value));
 $('#create-account')?.addEventListener('click',()=>authScreen('','signup',form.elements.email.value));
 $('#back-signin')?.addEventListener('click',()=>authScreen('','signin',form.elements.email.value));
 $('#clear-session').onclick=()=>safely(signOut);
}
async function passwordScreen(recovery=false){
 const {data:{user},error}=await db.auth.getUser();if(error)throw error;
 if(!user){authScreen('Sign in or request a password reset link first.');return;}
 const body=`<form id="set-password" class="stack"><label>Email address<input type="email" name="email" autocomplete="username" value="${h(user.email||'')}" readonly></label>${passwordFields()}<button type="submit" class="primary">Save password</button><p role="status" class="help"></p></form>`;
 if(recovery){$('#app').innerHTML=`<div class="auth"><h1>Set password</h1>${body}<button id="cancel-recovery" class="text-button">Back to sign in</button></div>`;$('#cancel-recovery').onclick=()=>safely(signOut);}
 else dialog('Set password',body);
 bindAuthForm($('#set-password'),async(form,result)=>{
  const password=checkPasswords(form);
  const {error}=await db.auth.updateUser({password});if(error)throw error;
  form.elements.password.value='';form.elements.confirm_password.value='';rememberRecovery(false);
  if(recovery){await openWorkspace();toast('Password saved. Use your email and password next time.');}
  else{result.textContent='Password saved. Use your email and password next time.';}
 });
}
async function signOut(){if(trackingLesson||pointQueue.length){toast('Stop route recording and save its points before signing out.',true);return;}const result=await db?.auth.signOut();if(result?.error)throw result.error;rememberRecovery(false);location.reload();}
function renderPupils(){
 $('#content').innerHTML=`<div class="heading"><div><h1>Pupils</h1></div><button id="add-pupil" class="primary">＋ Add pupil</button></div><div class="cards">${state.pupils.map(p=>{const total=lessonTotals(state.lessons.filter(l=>l.pupil_id===p.id));return `<article class="panel"><div class="pupil-avatar" style="background:${h(p.colour)}">${h(p.name.split(' ').map(n=>n[0]).slice(0,2).join(''))}</div><h3>${h(p.name)}</h3><p class="muted">${h(p.email)}</p><div class="detail-metrics"><div><strong>${total.hours.toFixed(1)}</strong><span>hours driven</span></div><div><strong>${total.miles.toFixed(1)}</strong><span>miles driven</span></div></div><button data-pupil="${p.id}">View lessons & progress</button></article>`;}).join('')||'<div class="empty">Add your first pupil to start booking lessons.</div>'}</div>`;
 $('#add-pupil').onclick=()=>{dialog('Add pupil',`<form id="pupil-form" class="stack"><label>Full name<input name="name" required maxlength="120"></label><label>Email address<input type="email" name="email" required></label><p class="help">The pupil chooses Create pupil account on the sign-in page, uses this email and sets a password. They confirm their email once, then can only view their own lessons, notes, routes and shared resources.</p><div class="dialog-actions"><button type="submit" class="primary">Add pupil</button></div></form>`);$('#pupil-form').onsubmit=e=>{e.preventDefault();safely(async()=>{const f=new FormData(e.target),p={name:f.get('name').trim(),email:f.get('email').trim().toLowerCase(),colour:['#dcf2d0','#dbeafa','#f5e6ce'][state.pupils.length%3]};if(!p.name)throw Error('Enter a name.');if(state.demo)state.pupils.push({...p,id:crypto.randomUUID()});else{const {error}=await db.from('pupils').insert(p);if(error)throw error;await reloadData();}$('#modal').close();render();toast('Pupil added.');});};};
 document.querySelectorAll('[data-pupil]').forEach(b=>b.onclick=()=>{state.view='progress';state.progressPupil=b.dataset.pupil;renderProgress(b.dataset.pupil);});
}
function locationFields(prefix,label,place){return `<div class="full"><label>${label}<div class="place-search"><input id="${prefix}-label" value="${h(place?.label||'')}" placeholder="Address or postcode" required autocomplete="off"><button type="button" id="${prefix}-find">Find</button></div></label><button type="button" id="${prefix}-map-pick" class="text-button">Select on map</button><div id="${prefix}-results"></div><p class="help" id="${prefix}-chosen">${place?'Location selected':'Enter the location, then search or select a point on the map.'}</p></div>`;}
async function mapRequest(body){if(state.demo)throw Error('Address search and road travel estimates become available when the map service is connected. Use the sample location buttons to try booking.');const {data,error}=await db.functions.invoke('maps',{body});if(error)throw Error('The map service is unavailable. Check its setup or use a manual travel allowance.');if(data.error)throw Error(data.error);return data;}
function bindLocation(prefix,places){$(`#${prefix}-map-pick`).onclick=()=>{const input=$(`#${prefix}-label`);if(!input.value.trim()){toast('Enter a label or address for this location.',true);return;}if(!window.L){toast('Map unavailable. Check your connection.',true);return;}const container=$(`#${prefix}-results`);container.innerHTML=`<div class="map" id="${prefix}-pick-map"></div><p class="help">Zoom in and tap the pickup or drop-off point.</p><button type="button" id="${prefix}-confirm-pin" disabled>Use selected point</button>`;if(map)map.remove();map=L.map(`${prefix}-pick-map`).setView(places[prefix]?[places[prefix].lat,places[prefix].lng]:[54,-2],places[prefix]?15:6);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);let selected=null,marker=null;map.on('click',e=>{selected={label:input.value.trim(),lat:e.latlng.lat,lng:e.latlng.lng};if(marker)marker.remove();marker=L.circleMarker(e.latlng,{radius:8,color:'#1e7847'}).addTo(map);$(`#${prefix}-confirm-pin`).disabled=false;});$(`#${prefix}-confirm-pin`).onclick=()=>{places[prefix]=selected;map.remove();map=null;container.innerHTML='';$(`#${prefix}-chosen`).textContent='✓ Location selected';$('#booking').dispatchEvent(new Event('input',{bubbles:true}));};};const input=$(`#${prefix}-label`);input.oninput=()=>{places[prefix]=null;$(`#${prefix}-chosen`).textContent='Select a result to confirm this location.';};$(`#${prefix}-find`).onclick=()=>safely(async()=>{if(input.value.trim().length<3)throw Error('Enter an address or postcode.');const features=state.demo?[{label:'Station car park (sample)',lat:51.4545,lng:-2.5879},{label:'College entrance (sample)',lat:51.465,lng:-2.59},{label:'Library (sample)',lat:51.447,lng:-2.6}]:(await mapRequest({action:'geocode',query:input.value})).places;const container=$(`#${prefix}-results`);container.innerHTML=features.map((f,i)=>`<button class="place-result" type="button" data-place="${i}">${h(f.label)}</button>`).join('')||'<p class="help">No matching locations found.</p>';container.querySelectorAll('button').forEach(b=>b.onclick=()=>{places[prefix]=features[Number(b.dataset.place)];input.value=places[prefix].label;container.innerHTML='';$(`#${prefix}-chosen`).textContent='✓ Location selected';});});}
function bookLesson(previous=null){
 if(!state.pupils.length){toast('Add a pupil first.');state.view='pupils';render();return;}
 const places={pickup:previous?.pickup||null,dropoff:previous?.dropoff||null};let quote=null;
 dialog('Book a lesson',`<form id="booking"><div class="form-grid">${locationFields('pickup','Pickup location',places.pickup)}${locationFields('dropoff','Drop-off location',places.dropoff)}<label>Pupil<select name="pupil_id">${state.pupils.map(p=>`<option value="${p.id}" ${previous?.pupil_id===p.id?'selected':''}>${h(p.name)}</option>`).join('')}</select></label><label>Date<input name="date" type="date" required value="${localDate(previous?addDays(previous.starts_at,7):today)}"></label><label>Start time<input name="time" type="time" required value="${previous?clock(previous.starts_at):'09:00'}"></label><label>Duration (minutes)<input name="duration" type="number" min="15" max="480" step="15" value="120" required></label><label>Lesson price (${config.currency})<input name="fee" type="number" min="0" step="0.01" value="80" required></label><label>Travel allowance<select name="travel_mode"><option value="automatic">Calculate from road travel time</option><option value="manual" ${state.demo?'selected':''}>Enter manually</option></select></label><label>Minutes before<input name="before" type="number" min="0" max="480" value="20"></label><label>Minutes to next lesson<input name="after" type="number" min="0" max="480" value="20"></label><label class="full">Lesson objectives<textarea name="objectives"></textarea></label><p class="help full">Objectives carry forward from this pupil’s latest completed lesson. You can edit them.</p></div><div id="travel-result" class="notice">Confirm the locations, date and time, then check availability.</div><div class="dialog-actions"><button id="check-times" type="button">Check availability</button><button id="save-booking" type="submit" class="primary" disabled>Book lesson</button></div></form>`);
 bindLocation('pickup',places);bindLocation('dropoff',places);
 const form=$('#booking');let objectivesEdited=false;
 const candidate=()=>{const f=new FormData(form),start=new Date(`${f.get('date')}T${f.get('time')}`);return {pupil_id:f.get('pupil_id'),starts_at:start.toISOString(),ends_at:new Date(start.getTime()+Number(f.get('duration'))*60000).toISOString(),fee:Number(f.get('fee')),pickup:places.pickup,dropoff:places.dropoff,objectives:f.get('objectives')};};
 const fillAims=()=>{if(!form.elements.date.value||!form.elements.time.value)return;if(!objectivesEdited)form.elements.objectives.value=previousAims(state.lessons,form.elements.pupil_id.value,candidate().starts_at);};fillAims();form.elements.objectives.oninput=()=>objectivesEdited=true;
 form.oninput=e=>{if(e.target.name!=='objectives'){quote=null;$('#save-booking').disabled=true;$('#travel-result').textContent='Booking details changed. Check availability again.';}if(['pupil_id','date','time'].includes(e.target.name))fillAims();};
 const check=async()=>{if(!form.reportValidity())return;await reloadData();const c=candidate();if(!c.pickup||!c.dropoff)throw Error('Select both pickup and drop-off locations first.');const {prev,next}=validateBooking(c,state.lessons);const signature=JSON.stringify([c,form.elements.travel_mode.value,form.elements.before.value,form.elements.after.value]);let before=0,after=0,source=form.elements.travel_mode.value;
  if(source==='automatic'){if(prev)before=(await mapRequest({action:'directions',from:prev.dropoff,to:c.pickup})).minutes;if(next)after=(await mapRequest({action:'directions',from:c.dropoff,to:next.pickup})).minutes;}
  else{before=prev?Number(form.elements.before.value):0;after=next?Number(form.elements.after.value):0;}
  validateBooking(c,state.lessons,before,after);if(JSON.stringify([candidate(),form.elements.travel_mode.value,form.elements.before.value,form.elements.after.value])!==signature)throw Error('Booking details changed. Check availability again.');quote={...c,signature,before,after,source,previousId:prev?.id||null,nextId:next?.id||null};$('#travel-result').textContent=`Available. ${before} minutes from the previous lesson; ${after} minutes to the next.${source==='manual'?' Using your manual allowances.':' Road estimates include a 5-minute margin; traffic may vary.'}`;$('#save-booking').disabled=false;};
 $('#check-times').onclick=()=>safely(check);
 form.onsubmit=e=>{e.preventDefault();safely(async()=>{if(!quote)throw Error('Check availability first.');const c=candidate();if(JSON.stringify([{...c,objectives:quote.objectives},form.elements.travel_mode.value,form.elements.before.value,form.elements.after.value])!==quote.signature)throw Error('Booking details changed. Check availability again.');const args={p_pupil_id:c.pupil_id,p_starts_at:c.starts_at,p_ends_at:c.ends_at,p_pickup:c.pickup,p_dropoff:c.dropoff,p_fee:c.fee,p_objectives:c.objectives,p_before:quote.before,p_after:quote.after,p_source:quote.source,p_previous:quote.previousId,p_next:quote.nextId,p_inherited:!objectivesEdited};
  if(state.demo){validateBooking(c,state.lessons,quote.before,quote.after);state.lessons.push({...c,id:crypto.randomUUID(),status:'scheduled',paid:false,objectives_inherited:!objectivesEdited,travel_before_minutes:quote.before,travel_source:quote.source,improved:'',needs_work:'',other:'',next_aims:''});const next=state.lessons.find(l=>l.id===quote.nextId);if(next){next.travel_before_minutes=quote.after;next.travel_source=quote.source;}}
  else{await rpc('book_lesson',args);await reloadData();}state.week=weekStart(c.starts_at);state.view='diary';$('#modal').close();render();toast('Lesson booked.');});};
}
const noteFields=[['objectives','Lesson objectives'],['improved','What has improved'],['needs_work','What needs more work'],['other','Other'],['next_aims','Aims for next time']];
async function lessonPoints(id){if(state.demo)return state.points.filter(p=>p.lesson_id===id);let result=[],offset=0;while(true){const {data,error}=await db.from('route_points').select('*').eq('lesson_id',id).order('recorded_at').order('id').range(offset,offset+999);if(error)throw error;result.push(...data);if(data.length<1000)return result;offset+=1000;}}
function openLesson(id){
 const l=state.lessons.find(l=>l.id===id);if(!l)return;state.selected=id;const admin=state.role==='admin';
 dialog(pupil(l.pupil_id)?.name||'Lesson',`<div class="row"><div><strong>${dateLabel(l.starts_at,{weekday:'long',day:'numeric',month:'long'})}</strong><p class="help">${clock(l.starts_at)} – ${clock(l.ends_at)} · ${h(l.status)}</p></div><span class="pill">${money(l.fee)} · ${l.paid?'Paid':'Unpaid'}</span></div><p class="help">Pickup: ${h(l.pickup.label)}<br>Drop-off: ${h(l.dropoff.label)}</p>${l.status==='completed'?`<div class="detail-metrics"><div><strong>${(minutes(l.started_at,l.ended_at)/60).toFixed(2)} hrs</strong><span>actual lesson time</span></div><div><strong>${(l.end_mileage-l.start_mileage).toFixed(1)} mi</strong><span>${l.start_mileage} → ${l.end_mileage}</span></div></div>`:''}${admin?`<div class="dialog-actions">${l.travel_source==='review'?'<button id="review-travel">Review travel time</button>':''}${l.status==='scheduled'?'<button id="start-lesson" class="primary lime">▶ Start lesson</button>':''}${l.status==='active'?'<button id="stop-lesson" class="primary">■ Stop lesson</button><button id="record-route">'+(trackingLesson===l.id?'Pause route recording':'Record route')+'</button>':''}<button id="payment">Mark as ${l.paid?'unpaid':'paid'}</button>${l.status==='scheduled'?'<button id="cancel-lesson" class="danger">Cancel lesson</button>':''}</div>`:''}${l.status==='active'?'<p class="route-status" id="route-status">'+h(trackingLesson===id?trackingMessage:'Route recording is not running on this device.')+'</p>':''}<form id="notes" class="stack">${noteFields.map(([key,label])=>admin?`<label>${label}<textarea name="${key}" maxlength="20000">${h(l[key])}</textarea></label>`:`<div><h3>${label}</h3><p class="read-note">${h(l[key]||'No notes added yet.')}</p></div>`).join('')}${admin?'<button type="submit" class="primary">Save lesson notes</button><span class="saved-line" id="notes-status" role="status"></span>':''}</form><h3 class="section-title">Lesson route</h3><p class="help">Recorded GPS trail. Gaps are left where tracking was interrupted.</p><div id="lesson-map" class="map"></div>${admin?'<label class="section-title">Import a GPX route<input type="file" id="import-gpx" accept=".gpx,application/gpx+xml"></label><p class="help">Import a timestamped GPX file recorded during this lesson. Points outside the actual lesson time are excluded.</p>':''}<h3 class="section-title">Resources from this lesson</h3><div id="lesson-resources" class="list"></div>${admin&&l.status==='completed'?'<div class="dialog-actions"><button id="next-lesson" class="primary lime">＋ Book next lesson</button></div>':''}`);
 const saveNotes=async()=>{const f=new FormData($('#notes'));const changes=Object.fromEntries(noteFields.map(([key])=>[key,f.get(key)]));if(state.demo){l.objectives_inherited=l.objectives_inherited!==false&&l.objectives===changes.objectives;Object.assign(l,changes);}else{await rpc('save_lesson_notes',{p_id:id,p_notes:changes});await reloadData();}$('#notes-status').textContent='Saved. Your pupil can see these notes.';};
 $('#notes').onsubmit=e=>{e.preventDefault();safely(saveNotes);};
 $('#review-travel')?.addEventListener('click',()=>safely(async()=>{await saveNotes();reviewTravel(id);}));
 $('#start-lesson')?.addEventListener('click',()=>safely(async()=>{await saveNotes();startForm(id);}));$('#stop-lesson')?.addEventListener('click',()=>safely(async()=>{await saveNotes();stopForm(id);}));
 $('#payment')?.addEventListener('click',()=>safely(async()=>{await saveNotes();if(state.demo)l.paid=!l.paid;else{await rpc('set_lesson_paid',{p_id:id,p_paid:!l.paid});await reloadData();}render();openLesson(id);}));
 $('#cancel-lesson')?.addEventListener('click',()=>{dialog('Cancel this lesson?',`<p>${h(pupil(l.pupil_id)?.name)} · ${dateLabel(l.starts_at)} at ${clock(l.starts_at)}</p><p class="help">The record and notes are kept. The time becomes available again.</p><div class="dialog-actions"><button id="keep-lesson">Keep lesson</button><button id="confirm-cancel" class="danger">Cancel lesson</button></div>`);$('#keep-lesson').onclick=()=>openLesson(id);$('#confirm-cancel').onclick=()=>safely(async()=>{if(state.demo)l.status='cancelled';else{await rpc('cancel_lesson',{p_id:id});await reloadData();}$('#modal').close();render();toast('Lesson cancelled.');});});
 $('#record-route')?.addEventListener('click',()=>safely(async()=>{await saveNotes();if(trackingLesson===id){await stopTracking();}else await startTracking(id);openLesson(id);}));
 $('#next-lesson')?.addEventListener('click',()=>safely(async()=>{await saveNotes();bookLesson(state.lessons.find(x=>x.id===id));}));
 $('#import-gpx')?.addEventListener('change',e=>{const file=e.target.files[0];if(file)safely(async()=>{await saveNotes();await importGpx(file,l);openLesson(id);});});
 void lessonPoints(id).then(points=>{if(state.selected===id&&$('#lesson-map'))drawMap('lesson-map',points,false,l.pickup);}).catch(e=>toast(e.message,true));
 showLessonResources(id);
}
function startForm(id){const l=state.lessons.find(x=>x.id===id);dialog('Start lesson',`<form id="start-form" class="stack"><label>Starting mileage<input type="number" name="mileage" min="0" step="0.1" required inputmode="decimal"></label><label><input type="checkbox" name="track">Record this device’s location</label><p class="notice">On iPhone, keep this page open and the screen on for route recording. It may pause when the phone locks or you switch apps. You can also import a route afterwards.</p><div class="dialog-actions"><button type="submit" class="primary lime">Start lesson</button></div></form>`);$('#start-form').onsubmit=e=>{e.preventDefault();safely(async()=>{const f=new FormData(e.target),m=Number(f.get('mileage'));if(state.lessons.some(x=>x.status==='active'&&x.id!==id))throw Error('Stop the current lesson before starting another.');if(state.demo){if(l.objectives_inherited!==false){const aims=previousAims(state.lessons,l.pupil_id,l.starts_at);if(aims)l.objectives=aims;}Object.assign(l,{status:'active',started_at:new Date().toISOString(),start_mileage:m});}else{await rpc('start_lesson',{p_id:id,p_mileage:m});await reloadData();}if(f.get('track'))await startTracking(id);render();openLesson(id);toast('Lesson started.');});};}
function stopForm(id){const l=state.lessons.find(x=>x.id===id);dialog('Stop lesson',`<form id="stop-form" class="stack"><p class="help">Starting mileage: ${l.start_mileage}</p><label>Ending mileage<input type="number" name="mileage" min="${l.start_mileage}" step="0.1" required inputmode="decimal"></label><div class="dialog-actions"><button type="submit" class="primary">Stop & complete lesson notes</button></div></form>`);$('#stop-form').onsubmit=e=>{e.preventDefault();safely(async()=>{const m=Number(new FormData(e.target).get('mileage'));if(m<l.start_mileage)throw Error('Ending mileage must be at least the starting mileage.');await stopTracking();if(state.demo)Object.assign(l,{status:'completed',ended_at:new Date().toISOString(),end_mileage:m});else{await rpc('finish_lesson',{p_id:id,p_mileage:m});await reloadData();}render();openLesson(id);toast('Lesson stopped. Add your notes and book the next lesson below.');});};}
function trackingStatus(message){trackingMessage=message;if($('#route-status'))$('#route-status').textContent=message;}
async function startTracking(id){
 if(!navigator.geolocation){toast('This browser does not support location recording.',true);return;}
 if(trackingLesson&&trackingLesson!==id)throw Error('Another lesson is recording on this device.');
 if(watchId!==null)return;trackingLesson=id;trackingStatus('Waiting for a location fix… Keep this page visible.');
 watchId=navigator.geolocation.watchPosition(position=>{const {latitude:lat,longitude:lng,accuracy}=position.coords;if(accuracy>100){trackingStatus('GPS accuracy is low. Waiting for a better fix…');return;}const p={id:crypto.randomUUID(),lesson_id:id,lat,lng,accuracy,recorded_at:new Date(position.timestamp).toISOString()};if(new Date(p.recorded_at)<new Date(state.lessons.find(l=>l.id===id)?.started_at))return;const last=pointQueue.at(-1);if(last&&new Date(p.recorded_at)-new Date(last.recorded_at)<3000)return;pointQueue.push(p);persistQueue();trackingStatus(`Recording · last fix ${clock(p.recorded_at)} · ±${Math.round(accuracy)} m · ${pointQueue.length} awaiting sync`);},e=>{trackingStatus(e.code===1?'Location permission was denied. Enable it in your browser settings, or import a route later.':`Location interrupted: ${e.message}. Keep the page open.`);if(e.code===1){navigator.geolocation.clearWatch(watchId);watchId=null;trackingLesson=null;clearInterval(syncTimer);wakeLock?.release().catch(()=>{});wakeLock=null;}},{enableHighAccuracy:true,maximumAge:0,timeout:20000});
 syncTimer=setInterval(()=>flushPoints().catch(e=>trackingStatus(`Route saved on this device; sync pending: ${e.message}`)),10000);
 try{wakeLock=await navigator.wakeLock?.request('screen');}catch{};
}
function persistQueue(){try{if(!state.demo)sessionStorage.setItem('pending-route-points',JSON.stringify(pointQueue));}catch{trackingStatus('Device storage is full. Keep this page open until points are synced.');}}
async function flushPoints(){if(flushPoints.running)return flushPoints.running;if(!pointQueue.length)return;const batch=pointQueue.slice(0,500);flushPoints.running=(async()=>{if(state.demo)state.points.push(...batch);else{const {error}=await db.from('route_points').upsert(batch,{onConflict:'id',ignoreDuplicates:true});if(error)throw error;}const ids=new Set(batch.map(p=>p.id));pointQueue=pointQueue.filter(p=>!ids.has(p.id));persistQueue();})();try{await flushPoints.running;}finally{flushPoints.running=null;}if(pointQueue.length)return flushPoints();}
async function stopTracking(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;clearInterval(syncTimer);try{await wakeLock?.release();}catch{}wakeLock=null;trackingLesson=null;await flushPoints();trackingStatus('Route recording stopped and points saved.');}
document.addEventListener('visibilitychange',()=>{if(trackingLesson){if(document.hidden)trackingStatus('Recording may be paused while this page is hidden.');else{trackingStatus('Page visible again. Waiting for GPS…');navigator.wakeLock?.request('screen').then(lock=>wakeLock=lock).catch(()=>{});}}});
window.addEventListener('beforeunload',e=>{if(trackingLesson||pointQueue.length){persistQueue();e.preventDefault();e.returnValue='';}});
async function importGpx(file,l){if(l.status!=='completed')throw Error('Complete the lesson before importing its route.');if(file.size>15*1024*1024)throw Error('Please use a GPX file smaller than 15 MB.');const xml=new DOMParser().parseFromString(await file.text(),'application/xml');if(xml.querySelector('parsererror'))throw Error('This is not a valid GPX file.');const points=[...xml.getElementsByTagNameNS('*','trkpt')].map(p=>({id:crypto.randomUUID(),lesson_id:l.id,lat:Number(p.getAttribute('lat')),lng:Number(p.getAttribute('lon')),accuracy:0,recorded_at:p.getElementsByTagNameNS('*','time')[0]?.textContent})).filter(p=>p.recorded_at&&Number.isFinite(p.lat)&&Math.abs(p.lat)<=90&&Number.isFinite(p.lng)&&Math.abs(p.lng)<=180&&new Date(p.recorded_at)>=new Date(l.started_at)&&new Date(p.recorded_at)<=new Date(l.ended_at));if(!points.length)throw Error('No timestamped points fall within this lesson’s actual start and stop times.');if(points.length>30000)throw Error('The route is too large. Export it with fewer GPS points.');if(state.demo)state.points.push(...points);else await rpc('import_lesson_route',{p_id:l.id,p_points:points.map(({id,lesson_id,...p})=>p)});toast(`${points.length} route points imported.`);}
function drawMap(target,points,fog=false,fallback=null){
 if(!window.L){$(`#${target}`).innerHTML='<div class="empty">The map could not load. Check your internet connection.</div>';return;}
 if(map)map.remove();map=L.map(target,{scrollWheelZoom:false}).setView(fallback?[fallback.lat,fallback.lng]:[54,-2],fallback?13:5);
 L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);
 const segments=splitTrack(points);const coordinates=segments.flat().map(p=>[p.lat,p.lng]);
 if(coordinates.length)map.fitBounds(L.latLngBounds(coordinates).pad(.2),{maxZoom:16});else L.popup().setLatLng(map.getCenter()).setContent('No route recorded yet.').openOn(map);
 segments.forEach(segment=>{if(segment.length===1)L.circleMarker([segment[0].lat,segment[0].lng],{radius:4,color:'#32905d'}).addTo(map);else L.polyline(segment.map(p=>[p.lat,p.lng]),{color:'#359d63',weight:4,opacity:.95}).addTo(map);});
 if(fog){const Fog=L.Layer.extend({onAdd(m){this.m=m;this.canvas=L.DomUtil.create('canvas','fog-layer');this.canvas.style.pointerEvents='none';m.getPanes().overlayPane.appendChild(this.canvas);m.on('moveend zoomend resize',this.redraw,this);this.redraw();},onRemove(m){m.off('moveend zoomend resize',this.redraw,this);this.canvas.remove();},redraw(){const m=this.m,s=m.getSize(),c=this.canvas;c.width=s.x;c.height=s.y;L.DomUtil.setPosition(c,m.containerPointToLayerPoint([0,0]));const ctx=c.getContext('2d');ctx.fillStyle='rgba(14,30,41,.86)';ctx.fillRect(0,0,s.x,s.y);ctx.globalCompositeOperation='destination-out';ctx.lineWidth=24;ctx.lineCap='round';ctx.lineJoin='round';segments.forEach(segment=>{ctx.beginPath();segment.forEach((p,i)=>{const q=m.latLngToContainerPoint([p.lat,p.lng]);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);});ctx.stroke();});ctx.globalCompositeOperation='source-over';}});new Fog().addTo(map);}
 setTimeout(()=>map?.invalidateSize(),100);
}
async function renderProgress(id){
 if(state.role==='admin')id=id||state.progressPupil;const p=pupil(id);if(!p)return;const lessons=state.lessons.filter(l=>l.pupil_id===id),totals=lessonTotals(lessons);
 $('#content').innerHTML=`<div class="heading"><div><h1>${state.role==='admin'?h(p.name):'My progress'}</h1></div>${state.role==='admin'?'<button id="back-pupils">Back to pupils</button>':''}</div><div class="stats"><div><span>Driving hours</span><strong>${totals.hours.toFixed(1)}<small>hours driven</small></strong></div><div><span>Distance driven</span><strong>${totals.miles.toFixed(1)}<small>miles</small></strong></div><div><span>Lessons completed</span><strong>${lessons.filter(l=>l.status==='completed').length}</strong></div></div><section class="panel"><div class="row"><h2>Roads explored</h2><label class="fog-toggle"><input id="fog" type="checkbox" checked>Fog of war</label></div><p class="help">Recorded GPS routes. Gaps indicate missing location data.</p><div id="progress-map" class="map"></div></section><h2 class="section-title">Upcoming lessons</h2><div class="list">${lessons.filter(l=>l.status==='active'||l.status==='scheduled'&&new Date(l.ends_at)>=new Date()).sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at)).map(progressLesson).join('')||'<div class="empty">No upcoming lessons.</div>'}</div><h2 class="section-title">Past lessons</h2><div class="list">${lessons.filter(l=>l.status==='completed'||l.status==='cancelled'||l.status==='scheduled'&&new Date(l.ends_at)<new Date()).sort((a,b)=>new Date(b.starts_at)-new Date(a.starts_at)).map(progressLesson).join('')||'<div class="empty">Your completed lessons will appear here.</div>'}</div>`;
 $('#back-pupils')?.addEventListener('click',()=>{state.view='pupils';render();});document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>openLesson(b.dataset.lesson));
 try{const points=(await Promise.all(lessons.filter(l=>l.status==='completed').map(l=>lessonPoints(l.id)))).flat();if(!$('#progress-map'))return;drawMap('progress-map',points,true);$('#fog').onchange=e=>drawMap('progress-map',points,e.target.checked);}catch(e){toast(e.message,true);}
}
function progressLesson(l){return `<button class="list-button" data-lesson="${l.id}"><span>${dateLabel(l.starts_at,{weekday:'short',day:'numeric',month:'long',year:'numeric'})} · ${clock(l.starts_at)}<small>${h(l.objectives||'Lesson')} · ${h(l.status)}</small></span><span>${l.paid?'✓ Paid':'Unpaid'} →</span></button>`;}
function renderResources(){
 const active=currentLesson();$('#content').innerHTML=`<div class="heading"><div><h1>Teaching library</h1><p>Images, diagrams and videos for your lessons.</p></div><button class="primary" id="upload">＋ Upload resource</button></div>${active?`<div class="notice">Current lesson: <strong>${h(pupil(active.pupil_id)?.name)}</strong> · ${clock(active.starts_at)}. Open a resource to add it to this lesson.</div>`:''}<div class="cards">${state.resources.map(r=>`<article class="panel"><div class="resource-file">${r.kind==='video'?'▷':'▧'}</div><h3>${h(r.title)}</h3><p class="muted">${h(r.kind)} · ${dateLabel(r.created_at)}</p><button data-resource="${r.id}">Open resource</button></article>`).join('')||'<div class="empty">No teaching resources uploaded.</div>'}</div>`;
 $('#upload').onclick=uploadResource;document.querySelectorAll('[data-resource]').forEach(b=>b.onclick=()=>safely(()=>openResource(b.dataset.resource)));
}
function currentLesson(){const active=state.lessons.filter(l=>l.status==='active');if(active.length===1)return active[0];const now=new Date(),scheduled=state.lessons.filter(l=>l.status==='scheduled'&&new Date(l.starts_at)<=now&&new Date(l.ends_at)>now);return scheduled.length===1?scheduled[0]:null;}
function uploadResource(){dialog('Upload teaching resource',`<form id="upload-form" class="stack"><label>Title<input name="title" required maxlength="180"></label><label>Image, diagram or video<input name="file" type="file" accept="image/png,image/jpeg,image/webp,video/mp4,video/webm,video/quicktime" required></label><p class="help">PNG, JPG, WebP, MP4, WebM or MOV. Maximum 50 MB. MP4 works best across devices.</p><button type="submit" class="primary">Upload resource</button></form>`);$('#upload-form').onsubmit=e=>{e.preventDefault();safely(async()=>{const f=new FormData(e.target),file=f.get('file'),types=['image/png','image/jpeg','image/webp','video/mp4','video/webm','video/quicktime'];if(!types.includes(file.type))throw Error('Please choose a supported image or video format.');if(file.size>50*1024*1024)throw Error('The maximum file size is 50 MB.');const resource={id:crypto.randomUUID(),title:f.get('title').trim(),kind:file.type.startsWith('video/')?'video':'image',mime_type:file.type,created_at:new Date().toISOString()};if(!resource.title)throw Error('Enter a title.');if(state.demo){resource.url=URL.createObjectURL(file);state.resources.push(resource);}else{resource.storage_path=`${resource.id}/${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await db.storage.from('teaching-resources').upload(resource.storage_path,file,{contentType:file.type,upsert:false});if(error)throw error;const {error:rowError}=await db.from('resources').insert(resource);if(rowError){await db.storage.from('teaching-resources').remove([resource.storage_path]);throw rowError;}await reloadData();}$('#modal').close();render();toast('Resource uploaded.');});};}
async function resourceUrl(resource){if(state.demo)return resource.url;const {data,error}=await db.storage.from('teaching-resources').createSignedUrl(resource.storage_path,3600);if(error)throw error;return data.signedUrl;}
async function openResource(id,lessonId=null){const r=state.resources.find(x=>x.id===id);if(!r)throw Error('Resource unavailable.');const url=await resourceUrl(r);const current=currentLesson();dialog(r.title,`${r.kind==='video'?`<video class="resource-view" controls playsinline src="${h(url)}"></video>`:`<img class="resource-view" src="${h(url)}" alt="${h(r.title)}">`}${state.role==='admin'?`<div class="section-title"><label>Add to lesson<select id="resource-lesson"><option value="">Select a lesson</option>${state.lessons.filter(l=>l.status!=='cancelled').sort((a,b)=>new Date(b.starts_at)-new Date(a.starts_at)).map(l=>`<option value="${l.id}" ${(lessonId||current?.id)===l.id?'selected':''}>${h(pupil(l.pupil_id)?.name)} · ${dateLabel(l.starts_at)} ${clock(l.starts_at)}</option>`).join('')}</select></label><div class="dialog-actions"><button id="attach-resource" class="primary">Add to lesson</button></div><p class="help">The pupil will be able to open this resource from their lesson summary.</p></div>`:''}`);$('#attach-resource')?.addEventListener('click',()=>safely(async()=>{const lesson_id=$('#resource-lesson').value;if(!lesson_id)throw Error('Choose a lesson first.');if(state.links.some(x=>x.lesson_id===lesson_id&&x.resource_id===id)){toast('This resource is already attached.');return;}if(state.demo)state.links.push({id:crypto.randomUUID(),lesson_id,resource_id:id});else{const {error}=await db.from('lesson_resources').insert({lesson_id,resource_id:id});if(error)throw error;await reloadData();}toast('Resource added to lesson.');}));}
function showLessonResources(id){const links=state.links.filter(x=>x.lesson_id===id);$('#lesson-resources').innerHTML=links.map(link=>{const r=state.resources.find(r=>r.id===link.resource_id);return r?`<button data-resource="${r.id}" class="list-button">${h(r.title)} <span>Open →</span></button>`:'';}).join('')||'<p class="help">No resources attached yet.</p>';$('#lesson-resources').querySelectorAll('button').forEach(b=>b.onclick=()=>safely(()=>openResource(b.dataset.resource,id)));}
if(!state.demo){try{pointQueue=JSON.parse(sessionStorage.getItem('pending-route-points')||'[]');}catch{pointQueue=[];}}
init();

function registerTools(){
 const context=document.modelContext;if(!context?.registerTool)return;
 const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
 const tools=[{name:'list_visible_lessons',title:'List lessons',description:'Read lessons visible to the signed-in account. Does not change records.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({lessons:visibleLessons().map(l=>({id:l.id,pupil:pupil(l.pupil_id)?.name,starts_at:l.starts_at,ends_at:l.ends_at,status:l.status,paid:l.paid}))})},{name:'open_lesson',title:'Open lesson',description:'Open a lesson record without starting the lesson or modifying it.',inputSchema:{type:'object',properties:{lesson_id:{type:'string'}},required:['lesson_id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:input=>{if(typeof input?.lesson_id!=='string'||!visibleLessons().some(l=>l.id===input.lesson_id))throw Error('Lesson not found or not accessible');openLesson(input.lesson_id);return {opened:input.lesson_id};}}];
 for(const tool of tools)try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
}

function reviewTravel(id){
 const lesson=state.lessons.find(l=>l.id===id);let previous;
 dialog('Review travel time',`<form id="travel-review" class="stack"><p class="help">The previous booking changed. Update the travel allowance into this lesson.</p><label>Travel allowance<select name="mode"><option value="automatic">Calculate road travel time</option><option value="manual" ${state.demo?'selected':''}>Enter manually</option></select></label><label>Minutes<input name="minutes" type="number" min="0" max="480" value="20" required></label><button class="primary" type="submit">Update travel time</button></form>`);
 $('#travel-review').onsubmit=e=>{e.preventDefault();safely(async()=>{const f=new FormData(e.target);await reloadData();previous=state.lessons.filter(l=>l.id!==id&&l.status!=='cancelled'&&new Date(l.ends_at)<=new Date(lesson.starts_at)).sort((a,b)=>new Date(b.ends_at)-new Date(a.ends_at))[0];const allowance=previous?(f.get('mode')==='automatic'?(await mapRequest({action:'directions',from:previous.dropoff,to:lesson.pickup})).minutes:Number(f.get('minutes'))):0;if(previous&&minutes(previous.ends_at,lesson.starts_at)<allowance)throw Error(`This needs ${allowance} minutes of travel. Cancel and rebook the lesson with enough time.`);if(state.demo){lesson.travel_before_minutes=allowance;lesson.travel_source=f.get('mode');}else{await rpc('update_travel_allowance',{p_id:id,p_previous:previous?.id||null,p_minutes:allowance,p_source:f.get('mode')});await reloadData();}render();openLesson(id);toast('Travel allowance updated.');});};
}
