import {PGlite} from '@electric-sql/pglite';
import {btree_gist} from '@electric-sql/pglite/contrib/btree_gist';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite({extensions:{btree_gist}});
await db.exec(`
create schema auth;create schema storage;create schema extensions;
create role anon;create role authenticated;
grant usage on schema public,auth,storage to anon,authenticated;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security;
grant select,insert,delete on storage.objects to authenticated;
`);
await db.exec(await fs.readFile(new URL('../supabase/migrations/202609160001_initial.sql',import.meta.url),'utf8'));
console.log('PASS: complete migration applies to PostgreSQL');
const instructor='11111111-1111-1111-1111-111111111111',alice='22222222-2222-2222-2222-222222222222',bob='33333333-3333-3333-3333-333333333333',unknown='44444444-4444-4444-4444-444444444444';
await db.exec(`insert into auth.users values('${instructor}','instructor@example.com',now()),('${alice}','alice@example.com',now()),('${bob}','bob@example.com',now()),('${unknown}','unknown@example.com',now());insert into public.instructors values('${instructor}');`);
async function asUser(id){await db.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);set role authenticated;`);}
async function denied(fn){await assert.rejects(fn);}
await asUser(instructor);
const a=(await db.query("insert into public.pupils(name,email) values('Alice','alice@example.com') returning id")).rows[0].id;
const b=(await db.query("insert into public.pupils(name,email) values('Bob','bob@example.com') returning id")).rows[0].id;
const place={label:'Sample pickup',lat:51.45,lng:-2.5};
async function book(pupil,start,end,prev=null,next=null,before=0,after=0,aims='',inherited=true){return (await db.query('select public.book_lesson($1,$2,$3,$4,$4,80,$5,$6,$7,\'manual\',$8,$9,$10) as id',[pupil,start,end,JSON.stringify(place),aims,before,after,prev,next,inherited])).rows[0].id;}
const first=await book(a,'2026-09-16T09:00Z','2026-09-16T11:00Z');
const second=await book(b,'2026-09-16T12:00Z','2026-09-16T14:00Z',first,null,20);
await denied(()=>book(a,'2026-09-16T10:00Z','2026-09-16T12:00Z',null,second));
await denied(()=>book(a,'2026-09-16T11:05Z','2026-09-16T11:40Z',first,second,20,20));
await denied(()=>book(a,'2026-09-17T09:00Z','2026-09-17T11:00Z',first));
console.log('PASS: overlaps, travel conflicts and stale diary snapshots rejected');
await db.query('select public.start_lesson($1,1000)',[first]);
await denied(()=>db.query('select public.start_lesson($1,1000)',[second]));
await denied(()=>db.query('select public.finish_lesson($1,999)',[first]));
await db.query('select public.finish_lesson($1,1025)',[first]);
await db.query('select public.save_lesson_notes($1,$2)',[first,JSON.stringify({objectives:'First objectives',next_aims:'Roundabouts'})]);
const third=await book(a,'2026-09-18T09:00Z','2026-09-18T11:00Z',second,null,20);
await db.query('select public.start_lesson($1,1025)',[third]);
assert.equal((await db.query('select objectives from public.lessons where id=$1',[third])).rows[0].objectives,'Roundabouts');
await db.query('select public.finish_lesson($1,1040)',[third]);
console.log('PASS: one active lesson, mileage validation, latest aims inherited');
const res=(await db.query("insert into public.resources(title,kind,mime_type,storage_path) values('Junction diagram','image','image/png','sample/diagram.png') returning id")).rows[0].id;
await db.query('insert into public.lesson_resources(lesson_id,resource_id) values($1,$2)',[first,res]);
await db.query("insert into storage.objects(bucket_id,name) values('teaching-resources','sample/diagram.png')");
await asUser(alice);await db.query('select public.claim_pupil_account()');
assert.equal((await db.query('select * from public.pupils')).rows.length,1);
assert.equal((await db.query('select * from public.lessons')).rows.length,2);
assert.equal((await db.query('select * from public.resources')).rows.length,1);
assert.equal((await db.query('select * from storage.objects')).rows.length,1);
await denied(()=>db.query('select public.set_lesson_paid($1,true)',[first]));
await denied(()=>db.query('select public.start_lesson($1,100)',[second]));
await denied(()=>db.query("insert into public.instructors values(auth.uid())"));
await denied(()=>db.query("insert into public.pupils(name,email) values('Fake','fake@example.com')"));
await denied(()=>db.query('update public.lessons set paid=true where id=$1',[first]));
await denied(()=>db.query('insert into public.lesson_resources(lesson_id,resource_id) values($1,$2)',[second,res]));
await asUser(bob);await db.query('select public.claim_pupil_account()');
assert.equal((await db.query('select * from public.lessons')).rows.length,1);
assert.equal((await db.query('select * from public.resources')).rows.length,0);
assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await asUser(unknown);await db.query('select public.claim_pupil_account()');
assert.equal((await db.query('select * from public.lessons')).rows.length,0);
assert.equal((await db.query('select * from public.pupils')).rows.length,0);
await db.exec('reset role;set role anon;');
await denied(()=>db.query('select * from public.lessons'));
await denied(()=>db.query('select public.is_instructor()'));
console.log('PASS: pupils isolated, pupil writes denied, private files isolated, strangers and anonymous users denied');
await asUser(instructor);
const actual=(await db.query('select started_at from public.lessons where id=$1',[first])).rows[0].started_at;
await db.query('select public.import_lesson_route($1,$2)',[first,JSON.stringify([{lat:51.4,lng:-2.5,recorded_at:actual}])]);
await denied(()=>db.query('select public.import_lesson_route($1,$2)',[first,JSON.stringify([{lat:51.4,lng:-2.5,recorded_at:'2000-01-01T00:00:00Z'}])]));
await asUser(alice);assert.equal((await db.query('select * from public.route_points')).rows.length,1);
await asUser(bob);assert.equal((await db.query('select * from public.route_points')).rows.length,0);
console.log('PASS: imported route timestamps validated and route privacy enforced');
await db.close();
