import {PGlite} from '@electric-sql/pglite';
import {btree_gist} from '@electric-sql/pglite/contrib/btree_gist';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite({extensions:{btree_gist}});
await db.exec(`
create schema auth;create schema storage;create schema extensions;
create role anon;create role authenticated;create role service_role bypassrls;
grant usage on schema public,auth,storage to anon,authenticated;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_app_meta_data jsonb default '{}');
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security;
grant select,insert,delete on storage.objects to authenticated;
`);
await db.exec(await fs.readFile(new URL('../supabase/migrations/202609160001_initial.sql',import.meta.url),'utf8'));
await db.exec(await fs.readFile(new URL('../supabase/migrations/202609170001_gpx_upload.sql',import.meta.url),'utf8'));
await db.exec(await fs.readFile(new URL('../supabase/migrations/202609170002_edit_lesson_times.sql',import.meta.url),'utf8'));
await db.exec(await fs.readFile(new URL('../supabase/migrations/202609170003_gpx_mileage.sql',import.meta.url),'utf8'));
console.log('PASS: all migrations apply to PostgreSQL');
const instructor='11111111-1111-1111-1111-111111111111',alice='22222222-2222-2222-2222-222222222222',bob='33333333-3333-3333-3333-333333333333',unknown='44444444-4444-4444-4444-444444444444';
await db.exec(`insert into auth.users(id,email,email_confirmed_at) values('${instructor}','instructor@example.com',now()),('${alice}','alice@example.com',now()),('${bob}','bob@example.com',now()),('${unknown}','unknown@example.com',now());insert into public.instructors values('${instructor}');`);
async function asUser(id){await db.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);set role authenticated;`);}
async function denied(fn){await assert.rejects(fn);}
await asUser(instructor);
const a=(await db.query("insert into public.pupils(name,email) values('Alice','alice@example.com') returning id")).rows[0].id;
const b=(await db.query("insert into public.pupils(name,email) values('Bob','bob@example.com') returning id")).rows[0].id;
const place={label:'Sample pickup',lat:51.45,lng:-2.5};
async function book(pupil,start,end,prev=null,next=null,before=0,after=0,aims='',inherited=true){return (await db.query('select public.book_lesson($1,$2,$3,$4,$4,80,$5,$6,$7,\'manual\',$8,$9,$10) as id',[pupil,start,end,JSON.stringify(place),aims,before,after,prev,next,inherited])).rows[0].id;}
const first=await book(a,'2026-09-16T09:00Z','2026-09-16T11:00Z');
const second=await book(b,'2026-09-16T12:00Z','2026-09-16T14:00Z',first,null,20);
await denied(()=>book(a,'2026-09-16T10:00Z','2026-09-16T12:00Z',null,second));
await denied(()=>book(a,'2026-09-16T11:05Z','2026-09-16T11:40Z',first,second,20,20));
await denied(()=>book(a,'2026-09-17T09:00Z','2026-09-17T11:00Z',first));
console.log('PASS: overlaps, travel conflicts and stale diary snapshots rejected');
await db.query('select public.start_lesson($1,1000)',[first]);
await denied(()=>db.query('select public.start_lesson($1,1000)',[second]));
await denied(()=>db.query('select public.finish_lesson($1,999)',[first]));
await db.query('select public.finish_lesson($1,1025)',[first]);
await db.query('select public.save_lesson_notes($1,$2)',[first,JSON.stringify({objectives:'First objectives',next_aims:'Roundabouts'})]);
const third=await book(a,'2026-09-18T09:00Z','2026-09-18T11:00Z',second,null,20);
await db.query('select public.start_lesson($1,1025)',[third]);
assert.equal((await db.query('select objectives from public.lessons where id=$1',[third])).rows[0].objectives,'Roundabouts');
await db.query('select public.finish_lesson($1,1040)',[third]);
console.log('PASS: one active lesson, mileage validation, latest aims inherited');
const res=(await db.query("insert into public.resources(title,kind,mime_type,storage_path) values('Junction diagram','image','image/png','sample/diagram.png') returning id")).rows[0].id;
await db.query('insert into public.lesson_resources(lesson_id,resource_id) values($1,$2)',[first,res]);
await db.query("insert into storage.objects(bucket_id,name) values('teaching-resources','sample/diagram.png')");
await asUser(alice);await db.query('select public.claim_pupil_account()');
assert.equal((await db.query('select * from public.pupils')).rows.length,1);
assert.equal((await db.query('select * from public.lessons')).rows.length,2);
assert.equal((await db.query('select * from public.resources')).rows.length,1);
assert.equal((await db.query('select * from storage.objects')).rows.length,1);
await denied(()=>db.query('select public.set_lesson_paid($1,true)',[first]));
await denied(()=>db.query('select public.start_lesson($1,100)',[second]));
await denied(()=>db.query("insert into public.instructors values(auth.uid())"));
await denied(()=>db.query("insert into public.pupils(name,email) values('Fake','fake@example.com')"));
await denied(()=>db.query('update public.lessons set paid=true where id=$1',[first]));
await denied(()=>db.query('insert into public.lesson_resources(lesson_id,resource_id) values($1,$2)',[second,res]));
await asUser(bob);await db.query('select public.claim_pupil_account()');
assert.equal((await db.query('select * from public.lessons')).rows.length,1);
assert.equal((await db.query('select * from public.resources')).rows.length,0);
assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await asUser(unknown);await db.query('select public.claim_pupil_account()');
assert.equal((await db.query('select * from public.lessons')).rows.length,0);
assert.equal((await db.query('select * from public.pupils')).rows.length,0);
await db.exec('reset role;set role anon;');
await denied(()=>db.query('select * from public.lessons'));
await denied(()=>db.query('select public.is_instructor()'));
console.log('PASS: pupils isolated, pupil writes denied, private files isolated, strangers and anonymous users denied');
await asUser(instructor);
const actual=(await db.query('select started_at from public.lessons where id=$1',[first])).rows[0].started_at;
await db.query('select public.import_lesson_route($1,$2)',[first,JSON.stringify([{lat:51.4,lng:-2.5,recorded_at:actual}])]);
await denied(()=>db.query('select public.import_lesson_route($1,$2)',[first,JSON.stringify([{lat:51.4,lng:-2.5,recorded_at:'2000-01-01T00:00:00Z'}])]));
await asUser(alice);assert.equal((await db.query('select * from public.route_points')).rows.length,1);
await asUser(bob);assert.equal((await db.query('select * from public.route_points')).rows.length,0);
console.log('PASS: imported route timestamps validated and route privacy enforced');
await asUser(instructor);
const route=[{lat:51.5,lng:-2.5,recorded_at:'2026-09-17T08:34:39Z',segment_id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'},{lat:51.51,lng:-2.51,recorded_at:'2026-09-17T09:42:27Z',segment_id:'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'}];
async function upload(id=second,points=route){return (await db.query('select public.save_gpx_route($1,$2,$3) as added',[id,'sample.gpx',JSON.stringify(points)])).rows[0].added;}
const before=(await db.query('select starts_at,ends_at,started_at,ended_at,start_mileage,end_mileage,status from public.lessons where id=$1',[second])).rows[0];
assert.equal(await upload(),2); // A scheduled lesson, with route timestamps outside its booked time.
assert.equal(await upload(),0); // Retry is idempotent.
assert.equal((await db.query('select route_file_name from public.lessons where id=$1',[second])).rows[0].route_file_name,'sample.gpx');
assert.deepEqual((await db.query('select starts_at,ends_at,started_at,ended_at,start_mileage,end_mileage,status from public.lessons where id=$1',[second])).rows[0],before);
assert.equal((await db.query('select segment_id from public.route_points where lesson_id=$1',[second])).rows.length,2);
await denied(()=>upload(second,[...route,{...route[0],lat:91}]));
await denied(()=>upload(second,[]));await denied(()=>upload(second,[{...route[0],recorded_at:null}]));
assert.equal((await db.query('select * from public.route_points where lesson_id=$1',[second])).rows.length,2);
await asUser(alice);assert.equal((await db.query('select * from public.route_points where lesson_id=$1',[second])).rows.length,0);await denied(()=>upload());
await asUser(bob);assert.equal((await db.query('select * from public.route_points where lesson_id=$1',[second])).rows.length,2);await denied(()=>upload());
await asUser(unknown);assert.equal((await db.query('select * from public.route_points')).rows.length,0);await denied(()=>upload());
await db.exec('reset role;set role anon;');await denied(()=>upload());
await asUser(instructor);
const getLesson=async id=>(await db.query('select * from public.lessons where id=$1',[id])).rows[0];
const snapshot=l=>Object.fromEntries(['starts_at','ends_at','started_at','ended_at','status'].map(k=>[k,l[k]]));
async function edit(l,changes={},previous=null,next=null,before=20,after=20){
 const c={...l,...changes};
 await db.query('select public.edit_lesson_times($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[l.id,c.starts_at,c.ends_at,c.started_at,c.ended_at,JSON.stringify(snapshot(l)),before,after,previous,next]);
}
let original=await getLesson(second);
const savedPoints=(await db.query('select * from public.route_points where lesson_id=$1 order by id',[second])).rows;
await edit(original,{starts_at:'2026-09-16T12:30Z',ends_at:'2026-09-16T14:30Z'},first,third);
let edited=await getLesson(second);assert.equal(new Date(edited.starts_at).toISOString(),'2026-09-16T12:30:00.000Z');assert.equal(edited.status,'scheduled');
assert.equal(edited.route_file_name,original.route_file_name);
assert.deepEqual((await db.query('select * from public.route_points where lesson_id=$1 order by id',[second])).rows,savedPoints);
await denied(()=>edit(original,{},first,third)); // Stale form cannot overwrite a newer edit.
await denied(()=>edit(edited,{starts_at:'2026-09-16T10:00Z',ends_at:'2026-09-16T12:00Z'},null,third));
await denied(()=>edit(edited,{starts_at:'2026-09-16T11:05Z',ends_at:'2026-09-16T12:00Z'},first,third));
await denied(()=>edit(edited,{starts_at:'2026-09-18T08:00Z',ends_at:'2026-09-18T08:50Z'},first,third));
await denied(()=>edit(edited,{starts_at:'2026-09-16T12:30Z',ends_at:'2026-09-16T12:00Z'},first,third));
await denied(()=>edit(edited,{ends_at:'2026-09-17T01:00Z'},first,third));
await denied(()=>edit(edited,{starts_at:'infinity',ends_at:'infinity'},first,third));
await denied(()=>edit(edited,{started_at:'2026-09-16T12:30Z'}));
await denied(()=>edit(edited,{starts_at:'2026-09-16T13:00Z',ends_at:'2026-09-16T15:00Z'},null,third));
assert.deepEqual(await getLesson(second),edited); // Invalid edits are atomic.
original=await getLesson(first);
await edit(original,{started_at:'2026-09-16T09:05Z',ended_at:'2026-09-16T10:35Z'});
let completed=await getLesson(first);
assert.equal((new Date(completed.ended_at)-new Date(completed.started_at))/3600000,1.5);
for(const key of ['starts_at','ends_at','start_mileage','end_mileage','paid','objectives','next_aims','status','travel_source'])assert.deepEqual(completed[key],original[key]);
await denied(()=>edit(completed,{ended_at:'2026-09-16T08:00Z'}));
await denied(()=>edit(completed,{started_at:null}));
await edit(completed,{starts_at:'2026-09-16T08:30Z',ends_at:'2026-09-16T10:30Z'},null,second);
await edit(edited,{starts_at:'2026-09-19T09:00Z',ends_at:'2026-09-19T11:00Z'},third,null);
assert.equal((await getLesson(third)).travel_source,'review');
assert.equal((await getLesson(second)).travel_before_minutes,20);
for(const person of [alice,bob,unknown]){await asUser(person);await denied(()=>edit(completed));}
await db.exec('reset role;set role anon;');await denied(()=>edit(completed));
await asUser(instructor);
const activeId=await book(a,'2026-09-20T09:00Z','2026-09-20T11:00Z',second);
await db.query('select public.start_lesson($1,1050)',[activeId]);
const active=await getLesson(activeId);
await edit(active,{started_at:new Date(Date.now()-3600000).toISOString()});
const activeEdited=await getLesson(activeId);
await denied(()=>edit(activeEdited,{started_at:'2099-01-01T09:00Z'}));
await denied(()=>edit(activeEdited,{ended_at:new Date().toISOString()}));
console.log('PASS: scheduled/completed/active edits, totals, unchanged routes and notes, travel gaps, stale edits, moved neighbours and read-only pupil access');
await asUser(instructor);await db.query('select public.cancel_lesson($1)',[second]);await denied(()=>upload());
const cancelled=await getLesson(second);await denied(()=>edit(cancelled));
console.log('PASS: full GPX saved and reread, timestamp mismatch allowed, retry deduplicated, segments retained, lesson totals unchanged, invalid input atomic, pupil/anonymous permissions preserved');
const gpsLesson=await book(b,'2026-09-21T09:00Z','2026-09-21T11:00Z',activeId);
const gpsPoints=[{lat:0,lng:0,recorded_at:'2026-09-21T09:05Z',segment_id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'},{lat:0,lng:0.01,recorded_at:'2026-09-21T09:06Z',segment_id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'},{lat:0,lng:1,recorded_at:'2026-09-21T10:55Z',segment_id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'}];
const saveGps=(id=gpsLesson,points=gpsPoints,complete=true)=>db.query('select public.save_gpx_lesson($1,$2,$3,$4)',[id,'gps.gpx',JSON.stringify(points),complete]);
await denied(()=>saveGps(gpsLesson,[gpsPoints[0]]));
assert.equal((await getLesson(gpsLesson)).route_distance_miles,null);
assert.equal((await db.query('select * from public.route_points where lesson_id=$1',[gpsLesson])).rows.length,0);
await saveGps();
const gpsDone=await getLesson(gpsLesson);
assert.equal(gpsDone.status,'completed');assert.equal(gpsDone.start_mileage,null);assert.equal(gpsDone.end_mileage,null);
assert.equal(new Date(gpsDone.started_at).toISOString(),'2026-09-21T09:05:00.000Z');assert.equal(new Date(gpsDone.ended_at).toISOString(),'2026-09-21T10:55:00.000Z');
assert.ok(Math.abs(gpsDone.route_distance_miles-0.690934195756)<0.000001);
await saveGps(gpsLesson,gpsPoints,false);
assert.equal((await getLesson(gpsLesson)).route_distance_miles,gpsDone.route_distance_miles);
await denied(()=>saveGps()); // Do not overwrite a completed lesson's driving times.
await edit(gpsDone,{ended_at:'2026-09-21T11:05Z'});
assert.equal((await getLesson(gpsLesson)).route_distance_miles,gpsDone.route_distance_miles);
await denied(()=>saveGps(activeId)); // Active timer cannot be silently completed by an old upload.
for(const user of [alice,bob,unknown]){await asUser(user);await denied(()=>saveGps(gpsLesson,gpsPoints,false));}
await asUser(bob);const ownGps=await getLesson(gpsLesson);assert.equal(ownGps.route_distance_miles,gpsDone.route_distance_miles);
await db.exec('reset role;set role anon;');await denied(()=>saveGps());
console.log('PASS: GPS mileage calculation and gaps, GPX-only completion without odometer, atomic invalid completion, retry deduplication, corrected times, pupil visibility and denied pupil writes');
await db.exec('reset role');
await db.exec(await fs.readFile(new URL('../supabase/migrations/202609170004_pupil_access.sql',import.meta.url),'utf8'));
await asUser(instructor);
await db.query('select public.edit_pupil_email($1,$2,$3)',[a,'ALICE.NEW@example.com','alice@example.com']);
assert.equal((await db.query('select email from public.pupils where id=$1',[a])).rows[0].email,'alice.new@example.com');
await denied(()=>db.query('select public.edit_pupil_email($1,$2,$3)',[a,'bob@example.com','alice.new@example.com']));
await denied(()=>db.query('select public.edit_pupil_email($1,$2,$3)',[a,'bad-email','alice.new@example.com']));
await denied(()=>db.query('select public.edit_pupil_email($1,$2,$3)',[a,'new@example.com','alice@example.com']));
await asUser(alice);await denied(()=>db.query('select public.edit_pupil_email($1,$2,$3)',[a,'new@example.com','alice.new@example.com']));
await denied(()=>db.query('select public.allow_pupil_code_attempt($1)',['a'.repeat(64)]));
const fresh='55555555-5555-5555-5555-555555555555',reset='66666666-6666-6666-6666-666666666666';
await db.exec('reset role');
await db.query('insert into auth.users(id,email,email_confirmed_at,raw_app_meta_data) values($1,$2,now(),$3),($4,$5,now(),$3)',[fresh,'private1@login.invalid',JSON.stringify({pupil_id:a,managed_pupil:true}),reset,'private2@login.invalid']);
await asUser(instructor);await denied(()=>db.query('select public.activate_pupil_code($1,$2,$3,$4)',[a,fresh,alice,'alice.new@example.com']));
await db.exec('reset role;set role service_role');
assert.equal((await db.query('select id,email,user_id,access_issued_at from public.pupils where id=$1',[a])).rows.length,1);
assert.equal((await db.query('select user_id from public.instructors')).rows.length,1);
await db.query('select public.activate_pupil_code($1,$2,$3,$4)',[a,fresh,alice,'alice.new@example.com']);
await denied(()=>db.query('select public.activate_pupil_code($1,$2,$3,$4)',[a,reset,alice,'alice.new@example.com']));
for(let i=0;i<8;i++)assert.equal((await db.query('select public.allow_pupil_code_attempt($1) as allowed',['a'.repeat(64)])).rows[0].allowed,true);
assert.equal((await db.query('select public.allow_pupil_code_attempt($1) as allowed',['a'.repeat(64)])).rows[0].allowed,false);
await asUser(alice);assert.equal((await db.query('select * from public.lessons')).rows.length,0);await db.query('select public.claim_pupil_account()');assert.equal((await db.query('select * from public.pupils')).rows.length,0);
await asUser(fresh);assert.equal((await db.query('select * from public.lessons')).rows.length,3); // Alice's three lessons, including the active sample.
await db.exec('reset role;set role service_role');
await db.query('select public.activate_pupil_code($1,$2,$3,$4)',[a,reset,fresh,'alice.new@example.com']);
await asUser(fresh);assert.equal((await db.query('select * from public.lessons')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await asUser(reset);assert.equal((await db.query('select * from public.lessons')).rows.length,3);
await asUser(bob);assert.equal((await db.query('select * from public.lessons where pupil_id=$1',[a])).rows.length,0);
console.log('PASS: instructor email edits, duplicate/stale rejection, service-only code activation, old login revocation, pupil isolation and atomic attempt limits');
await db.exec('reset role');
await db.exec(await fs.readFile(new URL('../supabase/migrations/202609170005_lesson_youtube.sql',import.meta.url),'utf8'));
await asUser(instructor);
const pin=async(lessonId=first,video='7lCDEYXw3mM',title='Junction recap')=>(await db.query('select public.pin_lesson_video($1,$2,$3) as id',[lessonId,video,title])).rows[0].id;
const video=await pin();assert.equal(await pin(),video);
assert.equal((await db.query('select * from public.lesson_videos where lesson_id=$1',[first])).rows.length,1);
await pin(first,'7lCDEYXw3mM','Updated title');
await denied(()=>pin(first,'bad','Test'));await denied(()=>pin(first,'7lCDEYXw3mM',' '));await denied(()=>pin(second));
await denied(()=>pin('77777777-7777-7777-7777-777777777777'));
await asUser(reset);assert.equal((await db.query('select title from public.lesson_videos')).rows[0].title,'Updated title');
await denied(()=>pin());await denied(()=>db.query('select public.unpin_lesson_video($1)',[video]));
await denied(()=>db.query("insert into public.lesson_videos(lesson_id,video_id,title) values($1,'7lCDEYXw3mM','Fake')",[first]));
await asUser(bob);assert.equal((await db.query('select * from public.lesson_videos')).rows.length,0);
await asUser(unknown);assert.equal((await db.query('select * from public.lesson_videos')).rows.length,0);
await db.exec('reset role;set role anon');await denied(()=>db.query('select * from public.lesson_videos'));await denied(()=>pin());
await asUser(instructor);await db.query('select public.unpin_lesson_video($1)',[video]);
assert.equal((await db.query('select pinned from public.lesson_videos where id=$1',[video])).rows[0].pinned,false);
await asUser(reset);assert.equal((await db.query('select * from public.lesson_videos')).rows.length,0);
await asUser(instructor);assert.equal(await pin(),video);
await asUser(reset);assert.equal((await db.query('select * from public.lesson_videos')).rows.length,1);
console.log('PASS: completed-lesson video pins, duplicate prevention, title update, invalid/cancelled targets, reversible unpin, pupil isolation and denied pupil writes');

await db.exec('reset role');
await db.exec(`create function auth.jwt() returns jsonb language sql stable as $$select jsonb_build_object('session_id',current_setting('request.jwt.session',true))$$;`);
await db.exec(await fs.readFile(new URL('../supabase/migrations/202609180001_pupil_activity_skills.sql',import.meta.url),'utf8'));
await asUser(instructor);
const grade=async(id=a,skill=1,rating=3,expected=0)=>(await db.query('select * from public.set_pupil_skill($1,$2,$3,$4)',[id,skill,rating,expected])).rows[0];
assert.equal((await grade()).rating,3);
await denied(()=>grade(a,1,4,0)); // stale forms cannot overwrite a newer rating
assert.equal((await grade(a,1,4,3)).rating,4);
for(const skill of [0,28,null])await denied(()=>grade(a,skill));
for(const rating of [-1,5,null])await denied(()=>grade(a,2,rating));
await denied(()=>grade(unknown));
await asUser(reset);assert.equal((await db.query('select rating from public.pupil_skill_ratings')).rows[0].rating,4);
await denied(()=>grade());await denied(()=>db.query('update public.pupil_skill_ratings set rating=0'));
await asUser(bob);assert.equal((await db.query('select * from public.pupil_skill_ratings')).rows.length,0);
await asUser(unknown);assert.equal((await db.query('select * from public.pupil_skill_ratings')).rows.length,0);
await denied(()=>db.query('select public.record_pupil_activity()'));
await db.exec('reset role;set role anon');await denied(()=>grade());await denied(()=>db.query('select public.record_pupil_activity()'));
await asUser(reset);
await db.exec("select set_config('request.jwt.session','aaaaaaaa-1111-1111-1111-111111111111',false)");
await db.query('select public.record_pupil_activity()');await db.query('select public.record_pupil_activity()');
assert.equal((await db.query('select * from public.pupil_activity')).rows.length,0);
await denied(()=>db.query('select * from public.pupil_activity_sessions'));
await denied(()=>db.query('update public.pupil_activity set visit_count=99'));
await asUser(instructor);
const activity=async()=>(await db.query('select * from public.pupil_activity where pupil_id=$1',[a])).rows[0];
assert.equal(Number((await activity()).sign_in_count),1);assert.equal(Number((await activity()).visit_count),1);
await db.query('select public.record_pupil_activity()'); // instructor preview must not create activity
assert.equal((await db.query('select * from public.pupil_activity')).rows.length,1);
await db.exec('reset role');await db.query("update public.pupil_activity set last_seen_at=now()-interval '31 minutes' where pupil_id=$1",[a]);
await asUser(reset);await db.query('select public.record_pupil_activity()');
await asUser(instructor);assert.equal(Number((await activity()).visit_count),2);assert.equal(Number((await activity()).sign_in_count),1);
await asUser(reset);await db.exec("select set_config('request.jwt.session','aaaaaaaa-2222-2222-2222-222222222222',false)");await db.query('select public.record_pupil_activity()');
await asUser(instructor);assert.equal(Number((await activity()).sign_in_count),2);assert.equal(Number((await activity()).visit_count),3);
await asUser(reset);await db.exec("select set_config('request.jwt.session','aaaaaaaa-1111-1111-1111-111111111111',false)");await db.query('select public.record_pupil_activity()');
await asUser(instructor);assert.equal(Number((await activity()).sign_in_count),2);assert.equal(Number((await activity()).visit_count),3);
await asUser(alice);await denied(()=>db.query('select public.record_pupil_activity()')); // retired pupil identity
console.log('PASS: all skill bounds, stale edits, own-pupil read access, denied pupil writes; activity session deduplication, visit gaps, preview exclusion and instructor-only metrics');


await db.exec('reset role');
await db.exec(await fs.readFile(new URL('../supabase/migrations/202609180002_detailed_skills.sql',import.meta.url),'utf8'));
await asUser(instructor);
const detail=async(category=1,item=1,rating=3,expected=0)=>(await db.query('select * from public.set_pupil_detail_rating($1,$2,$3,$4,$5)',[a,category,item,rating,expected])).rows[0];
assert.equal((await detail()).rating,3);await denied(()=>detail(1,1,4,0));
for(const args of [[0,1],[37,1],[1,17],[5,38],[36,13],[1,0],[1,1,5],[1,1,-1]])await denied(()=>detail(...args));
assert.equal((await detail(5,37)).rating,3);assert.equal((await detail(36,12)).rating,3);
const skillPin=async(refresh=false)=>(await db.query('select * from public.pin_lesson_skill($1,1,$2)',[first,refresh])).rows[0];
const detailSnapshot=await skillPin();assert.equal(detailSnapshot.points,3);assert.equal(detailSnapshot.item_count,16);
await detail(1,1,4,3);assert.equal((await skillPin()).points,3);assert.equal((await skillPin(true)).points,4);
assert.equal((await db.query('select * from public.lesson_skill_pins')).rows.length,1);
await denied(()=>db.query('select public.pin_lesson_skill($1,1)',[second])); // cancelled
await denied(()=>db.query('select public.pin_lesson_skill($1,37)',[first]));
assert.equal((await db.query('select rating from public.pupil_skill_ratings where pupil_id=$1',[a])).rows[0].rating,4); // old grades preserved
await asUser(reset);assert.equal((await db.query('select * from public.pupil_detail_ratings')).rows.length,3);
assert.equal((await db.query('select points from public.lesson_skill_pins')).rows[0].points,4);
await denied(()=>detail());await denied(()=>skillPin());await denied(()=>db.query('select public.unpin_lesson_skill($1)',[detailSnapshot.id]));
await denied(()=>db.query('update public.pupil_detail_ratings set rating=4'));await denied(()=>db.query('update public.lesson_skill_pins set points=64'));
for(const user of [bob,unknown]){await asUser(user);assert.equal((await db.query('select * from public.pupil_detail_ratings')).rows.length,0);assert.equal((await db.query('select * from public.lesson_skill_pins')).rows.length,0);}
await db.exec('reset role;set role anon');await denied(()=>detail());await denied(()=>skillPin());
await asUser(instructor);await db.query('select public.unpin_lesson_skill($1)',[detailSnapshot.id]);
await asUser(reset);assert.equal((await db.query('select * from public.lesson_skill_pins')).rows.length,0);
await asUser(instructor);assert.equal((await skillPin()).id,detailSnapshot.id);assert.equal((await skillPin()).points,4);
console.log('PASS: detailed syllabus bounds, preserved old grades, stale edits, read-only own-pupil access, immutable lesson snapshots, explicit refresh, reversible unpin and cancelled lesson rejection');

await db.exec('reset role');
await db.exec(await fs.readFile(new URL('../supabase/migrations/202609180003_ai_skill_review.sql',import.meta.url),'utf8'));
await asUser(instructor);
const aiSummary=async(text='Mirrors needed reminders',expected='')=>(await db.query('select * from public.save_lesson_skill_summary($1,$2,$3)',[first,text,expected])).rows[0];
assert.equal((await aiSummary()).summary,'Mirrors needed reminders');await denied(()=>aiSummary('stale',''));
await denied(()=>aiSummary('a'.repeat(6001),'Mirrors needed reminders'));
const batch=async(changes,id=first,pins=[],items=[])=>(await db.query('select public.apply_lesson_skill_ratings($1,$2,$3,$4) as result',[id,JSON.stringify(changes),pins,JSON.stringify(items)])).rows[0].result;
const c={category_id:9,item_id:6,rating:2,expected:0};
await denied(()=>batch([c,{category_id:1,item_id:1,rating:3,expected:0}]));
assert.equal((await db.query('select * from public.pupil_detail_ratings where category_id=9')).rows.length,0);
await denied(()=>batch([c,c]));await denied(()=>batch([{...c,item_id:99}]));await denied(()=>batch([{...c,rating:2.1}]));await denied(()=>batch([{...c,rating:null}]));
await denied(()=>batch([c],second));await denied(()=>batch([]));assert.equal((await batch([c],first,[9])).ratings[0].rating,2);
assert.equal((await db.query('select points from public.lesson_skill_pins where category_id=9')).rows[0].points,2);
assert.equal((await batch([],first,[19])).pins[0].category_id,19);
await denied(()=>batch([{...c,rating:3,expected:2}],first,[37]));
assert.equal((await db.query('select rating from public.pupil_detail_ratings where category_id=9')).rows[0].rating,2);
const itemPin={category_id:9,item_id:6,title:'Mirror checks before slowing'};
assert.equal((await batch([],first,[],[itemPin])).detail_pins[0].rating,2);
await batch([{...c,rating:3,expected:2}],first,[],[itemPin]);
assert.equal((await db.query('select rating from public.lesson_detail_skill_pins')).rows[0].rating,2); // snapshot preserved
await db.query('select public.pin_lesson_detail_skill($1,9,6,$2,true)',[first,itemPin.title]);
assert.equal((await db.query('select rating from public.lesson_detail_skill_pins')).rows[0].rating,3);
await denied(()=>batch([{...c,rating:4,expected:3}],first,[],[{...itemPin,item_id:99}]));
assert.equal((await db.query('select rating from public.pupil_detail_ratings where category_id=9')).rows[0].rating,3);
await asUser(reset);assert.equal((await db.query('select * from public.lesson_detail_skill_pins')).rows.length,1);await denied(()=>db.query('select public.pin_lesson_detail_skill($1,9,6,$2)',[first,itemPin.title]));
await asUser(bob);assert.equal((await db.query('select * from public.lesson_detail_skill_pins')).rows.length,0);
await asUser(instructor);
assert.equal((await skillPin()).points,4); // saved lesson scores do not change
assert.equal((await db.query('select public.reserve_skill_suggestion($1) as ok',[first])).rows[0].ok,true);
assert.equal((await db.query('select public.reserve_skill_suggestion($1) as ok',[first])).rows[0].ok,false);
await denied(()=>db.query('update public.instructor_ai_usage set request_count=0'));
await db.exec("reset role;update public.instructor_ai_usage set request_count=100,last_requested_at=now()-interval '1 minute'");await asUser(instructor);
assert.equal((await db.query('select public.reserve_skill_suggestion($1) as ok',[first])).rows[0].ok,false);
await db.exec("reset role;update public.instructor_ai_usage set usage_day=current_date-1,last_requested_at=now()-interval '1 minute'");await asUser(instructor);
assert.equal((await db.query('select public.reserve_skill_suggestion($1) as ok',[first])).rows[0].ok,true);
for(const user of [reset,bob,unknown]){await asUser(user);assert.equal((await db.query('select * from public.lesson_skill_reviews')).rows.length,0);await denied(()=>aiSummary());await denied(()=>batch([c]));await denied(()=>db.query('select public.reserve_skill_suggestion($1)',[first]));}
await db.exec('reset role;set role anon');await denied(()=>aiSummary());await denied(()=>batch([c]));await denied(()=>db.query('select * from public.lesson_skill_reviews'));
console.log('PASS: private AI summaries, stale-summary protection, atomic reviewed rating batches, role isolation, cancelled lessons and persistent request limits');
await db.close();
